apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myd
  name: mydeploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myd
    spec:
      containers:
      - image: httpid
        name: httpd
        resources: {}
status: {}
