apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myd
  name: mydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myd
    spec:
      containers:
      - image: wordpress:5.1.1-php7.3-apache
        name: apache-webserver-php
        resources: {}
status: {}
