apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myd
  name: myd
spec:
  ports:
  - port: {{ .Values.myservice.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: myd
  type: {{ .Values.myservice.type }}
status:
  loadBalancer: {}

