apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myservice
  name: myservice
spec:
  ports:
  - port: {{ .Values.myservice.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: myservice
  type: {{ .Values.myservice.type }}
status:
  loadBalancer: {}

