apiVersion: apps/v1
kind: Deployment
metadata: 
  name: wpress
  labels:
    app: wp
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: wp
  template:
    metadata:
      labels:
	app: wp 
    spec:
      nodename: ip-172-31-16-38.ec2.internal
      containers:
       - name: wp
         image: wordpress:5.1.1-php7.3-apache